# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y7U7wA6d_7jxzoikyvWuYJjHljPSdym4
"""

Dict = {'Section 11(5) of the Arbitration and Conciliation Act':'Arbitration Petition','Articles 132':'Civil Appeal',
        'Section 130E of the Customs Act':'Civil Appeal',
        'Section 35L of the Central Excise and Salt Act':'Civil Appeal','Section 23':'Civil Appeal',
        'Section 27A of the Consumer Protection Act':'Civil Appeal','Section 19(1)(b) of the Contempt of Courts Act':'Civil Appeal',
        'Section 38 of the Advocates Act':'Civil Appeal','Section 116A of the Representation of People Act':'Civil Appeal',
        'Section 18 of the Telecom Regulatory Authority of India Act':'Civil Appeal',
       'Section 15Z':'Civil Appeal','Section 261':'Civil Appeal',
        'Section 53T':'Civil Appeal',
        'Sections 30':'Civil Appeal','Sections 31':'Civil Appeal','Section 125':'Civil Appeal',
       'Section 29(1)':'Civil Appeal','Section 22':'Civil Appeal','Section 10':'Civil Appeal',
        'Section 423 of the Companies Act':'Civil Appeal',
        'Sections 17 of the Airport Economic Regulatory Authority of India Act':'Civil Appeal','Section 376':'Criminal'
       ,'Section 302':'Criminal','Section 3':'Criminal','Indian Penal Code':'Criminal','Articles 132(1)':'Criminal','IPC':'Criminal',
       'Section 11 of the Competition Act':'Special Reference Case','Section 14(1) of the Right to Information Act':'Speacial Reference Case',
       'Right to Information Act':'Special Reference Case',
       'Section 27(3A) of the Wealth Tax Act':'Special Reference Case',
       'Section 11(3) of the Companies Act':'Special Reference Case',
        'Article 139A(1)':'Transfer Petition','Article 139A(2)':'Transfer Petition','Section 25 of the Code of Civil Procedure':'Tranfer Petition',
        'Section 406 of the Code of Criminal Procedure':'Transfer Petition',
        'Section 11 of the Terrorist Affected':'Transfer Petition',
        'Article 32':'Writ Petition','Article 137':'Review Case','WRIT':'Writ Petition','Article 39A':'Civil Appeal'
       }